version 20230616.051920_builder.r1345402;
system {
    host-name ce-c1;
    root-authentication {
        encrypted-password "$6$lB5c6$Zeud8c6IhCTE6hnZxXBl3ZMZTC2hOx9pxxYUWTHKW1oC32SATWLMH2EXarxWS5k685qMggUfFur1lq.o4p4cg1";
        ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"; ## SECRET-DATA
    }
    login {
        user user {
            uid 2000;
            class operator;
            authentication {
                ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"; ## SECRET-DATA
            }
        }
    }
    services {
        ssh {
            root-login deny-password;
        }
        netconf {
            ssh;
        }
    }
}
interfaces {
    eth1 {
        unit 0 {
            family inet {
                address 172.16.30.2/30;
            }
        }
    }
    eth2 {
        unit 0 {
            family inet {
                address 8.8.8.254/24;
            }
        }
    }
}
routing-options {
    router-id 172.16.30.2;
    autonomous-system 15169;
}
policy-options {
    policy-statement LAN-EXPORT {
        term LAN {
            from {
                protocol direct;
                interface eth2;
            }
            then accept;
        }
        then reject;
    }
}
protocols {
    bgp {
        group PE {
            type external;
            export LAN-EXPORT;
            peer-as 7539;
            family inet {
                unicast;
            }
            neighbor 172.16.30.1;
        }
    }
}
