version 20230616.051920_builder.r1345402;
system {
    host-name p3;
    root-authentication {
        encrypted-password "$6$lB5c6$Zeud8c6IhCTE6hnZxXBl3ZMZTC2hOx9pxxYUWTHKW1oC32SATWLMH2EXarxWS5k685qMggUfFur1lq.o4p4cg1";
        ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"; ## SECRET-DATA
    }
    login {
        user user {
            uid 2000;
            class super-user;
            authentication {
                ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"; ## SECRET-DATA
            }
        }
    }
    services {
        ssh {
            root-login deny-password;
        }
        netconf {
            ssh;
        }
    }
}
interfaces {
    eth1 {
        unit 0 {
            family inet {
                address 10.0.0.10/30;
            }
            family mpls;
        }
    }
    eth2 {
        unit 0 {
            family inet {
                address 10.0.0.14/30;
            }
            family mpls;
        }
    }
    eth3 {
        unit 0 {
            family inet {
                address 10.0.0.21/30;
            }
            family mpls;
        }
    }
    eth4 {
        unit 0 {
            family inet {
                address 10.0.0.25/30;
            }
            family mpls;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.0.23/32;
            }
        }
    }
}
routing-options {
    router-id 10.255.0.23;
    autonomous-system 7539;
    rib mpls.0;
}
