set system host-name pe1
set chassis fpc 0 lite-mode
set system root-authentication encrypted-password "$6$lB5c6$Zeud8c6IhCTE6hnZxXBl3ZMZTC2hOx9pxxYUWTHKW1oC32SATWLMH2EXarxWS5k685qMggUfFur1lq.o4p4cg1"
set system root-authentication ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"
set system login user user uid 2000
set system login user user class super-user
set system login user user authentication ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpxid3kNcNm9iyJrzVOGiYCQMcWRnMTzwEy6tUaWU/r judge@nnie-2026"
set system services ssh root-login deny-password
set system services netconf ssh
set interfaces ge-0/0/0 mtu 9500
set interfaces ge-0/0/0 unit 0 family inet address 10.0.0.1/30
set interfaces ge-0/0/0 unit 0 family mpls
set interfaces ge-0/0/1 unit 0 family inet address 172.16.10.1/30
set interfaces ge-0/0/2 unit 0 family inet address 172.16.20.1/30
set interfaces ge-0/0/3 unit 0 family inet address 172.16.30.1/30
set interfaces ge-0/0/4 flexible-vlan-tagging
set interfaces ge-0/0/4 encapsulation flexible-ethernet-services
set interfaces ge-0/0/4 unit 100 encapsulation vlan-bridge
set interfaces ge-0/0/4 unit 100 vlan-id 100
set interfaces ge-0/0/5 flexible-vlan-tagging
set interfaces ge-0/0/5 encapsulation flexible-ethernet-services
set interfaces ge-0/0/5 unit 100 encapsulation vlan-bridge
set interfaces ge-0/0/5 unit 100 vlan-id 100
set interfaces ge-0/0/5 unit 200 encapsulation vlan-bridge
set interfaces ge-0/0/5 unit 200 vlan-id 200
set interfaces ge-0/0/6 flexible-vlan-tagging
set interfaces ge-0/0/6 encapsulation flexible-ethernet-services
set interfaces ge-0/0/6 unit 200 encapsulation vlan-bridge
set interfaces ge-0/0/6 unit 200 vlan-id 200
set interfaces ge-0/0/7 unit 0 family inet address 172.16.40.1/30
set interfaces ge-0/0/8 unit 0 family inet address 172.16.41.1/30
set interfaces irb unit 100 virtual-gateway-accept-data
set interfaces irb unit 100 virtual-gateway-v4-mac 00:00:5e:00:01:01
set interfaces irb unit 100 family inet address 202.5.12.1/24 preferred
set interfaces irb unit 100 family inet address 202.5.12.1/24 virtual-gateway-address 202.5.12.254
set interfaces irb unit 200 virtual-gateway-accept-data
set interfaces irb unit 200 virtual-gateway-v4-mac 00:00:5e:00:01:01
set interfaces irb unit 200 family inet address 211.76.161.1/24 preferred
set interfaces irb unit 200 family inet address 211.76.161.1/24 virtual-gateway-address 211.76.161.254
set interfaces lo0 unit 0 family inet address 10.255.0.11/32
set routing-options router-id 10.255.0.11
set routing-options autonomous-system 7539
set routing-options rib mpls.0
